[project]
name = "micrograd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=6.31.0",
    "jupyter>=1.1.1",
    "torch>=2.8.0",
]
